// Mocks generated by Mockito 5.2.0 from annotations
// in zemoga_flutter_app/test/features/main/domain/usecases/get_post_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:zemoga_flutter_app/core/error/failure.dart' as _i5;
import 'package:zemoga_flutter_app/features/main/data/models/post_model.dart'
    as _i7;
import 'package:zemoga_flutter_app/features/main/domain/entities/post.dart'
    as _i6;
import 'package:zemoga_flutter_app/features/main/domain/repositories/post_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i3.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Post>?>?> getPostsList() =>
      (super.noSuchMethod(Invocation.method(#getPostsList, []),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.Post>?>?>.value())
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Post>?>?>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> updateFavoritePost(
          _i7.PostModel? post) =>
      (super.noSuchMethod(Invocation.method(#updateFavoritePost, [post]),
              returnValue: Future<_i2.Either<_i5.Failure, bool>>.value(
                  _FakeEither_0<_i5.Failure, bool>()))
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
