// Mocks generated by Mockito 5.2.0 from annotations
// in zemoga_flutter_app/test/features/details/domain/usecases/get_comments_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:zemoga_flutter_app/core/error/failure.dart' as _i5;
import 'package:zemoga_flutter_app/features/details/domain/entities/comment.dart'
    as _i7;
import 'package:zemoga_flutter_app/features/details/domain/entities/user.dart'
    as _i6;
import 'package:zemoga_flutter_app/features/details/domain/repositories/details_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [DetailsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetailsRepository extends _i1.Mock implements _i2.DetailsRepository {
  MockDetailsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.User?>?> getUser(int? id) =>
      (super.noSuchMethod(Invocation.method(#getUser, [id]),
              returnValue: Future<_i4.Either<_i5.Failure, _i6.User?>?>.value())
          as _i3.Future<_i4.Either<_i5.Failure, _i6.User?>?>);
  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i7.Comment>?>?> getComments() =>
      (super.noSuchMethod(Invocation.method(#getComments, []),
              returnValue:
                  Future<_i4.Either<_i5.Failure, List<_i7.Comment>?>?>.value())
          as _i3.Future<_i4.Either<_i5.Failure, List<_i7.Comment>?>?>);
}
